#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/

###################
## configuration ##
###################

## workspace name
## font needed wuncon-siji
#bspc monitor -d '' '' '' '' '' '' '' ''
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 'shell' 'web' 'social' 'code' 'file' 'rdp'

# TODO: Make workspaces disappear when there is nothing in them

## common bspwm configuration
bspc config border_width            2
bspc config window_gap         	    16
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config top_padding             42 #24

bspc config focused_border_color    "#d8dee8"
bspc config normal_border_color     "#2f343f"

##################
## window rules ##
##################

## workspace 1 (labs)
#bspc rule -a URxvt desktop='^1' follow=on focus=on

## workspace 2 (web browsers)
#bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
#bspc rule -a Chromium desktop='^2' follow=on focus=on
#bspc rule -a Google-chrome desktop='^2' follow=on focus=on

## work space 3 (social)
#bspc rule -a Rambox desktop='^3' follow=off focus=off

## workspace 4 (code)
#bspc rule -a Code desktop='^4' follow=on focus=on
#bspc rule -a code-oss desktop='^4' follow=on focus=on

#bspc rule -a jetbrains-rider desktop='^4' follow=on focus=on

## workspace 5 (file-manager)
#bspc rule -a Thunar desktop='^5' follow=on focus=on

## workspace 6 (rdp)
#bspc rule -a Remmina desktop='^6' follow=on focus=on
#bspc rule -a Remmina Remote Desktop Client desktop='^6' follow=on focus=on

## workspace 7 (multimedia)
#bspc rule -a Audacity desktop='^6' follow=on focus=on
#bspc rule -a Vlc desktop='^6' follow=on focus=on
#bspc rule -a mpv desktop='^6' follow=on focus=on
#bspc rule -a Ghb desktop='^6' follow=on focus=on
#bspc rule -a Xfburn desktop='^6' follow=on focus=on

## workspace 8 (system-settings)
#bspc rule -a Lxappearance desktop='^8' state=floating follow=on
#bspc rule -a Xfce4-settings-manager desktop='^8' state=floating follow=on
#bspc rule -a Lightdm-gtk-greeter-settings desktop='^8' state=floating follow=on
#bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on
#bspc rule -a Lxtask desktop='^8' state=floating follow=on
#bspc rule -a GParted desktop='^8' follow=on focus=on
#bspc rule -a Pavucontrol desktop='^8' state=floating follow=on
#bspc rule -a Exo-helper-1 desktop='^8' state=floating follow=on
#bspc rule -a Lxrandr desktop='^8' state=floating follow=on
#bspc rule -a Arandr desktop='^8' state=floating follow=on

## need to be floating
bspc rule -a Viewnior state=floating follow=on
bspc rule -a feh state=floating follow=on

## don't manage my conky & systemtray :/
#bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

###############
## AUTOSTART ##
###############

# Update betterlockscreen with current wallpaper
betterlockscreen -u ~/.wallpaper.jpg &

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

# Reload compton
pkill compton
compton -b &

# Start urxvt deamon
urxvtd -q &

# Start udiskie deamon
udiskie &

# system tray
#pkill stalonetray
#stalonetray &

# network applet
#nm-applet &

# clipboard manager
#pkill clipit
#clipit &

# volume icon
#pkill volumeicon
#volumeicon &

# Start keybind daemon (sxhkd)
pkill sxhkd
sxhkd &

# Start music player
mpd &

# Reload the xsettingsd, a minimal X settings daemon
pkill xsettingsd
xsettingsd &

# Set the wallpaper
feh --bg-fill ~/.wallpaper.jpg

# Start notification manager (dunst)
pkill dunst
dunst &

# Reload the cursor theme
xsetroot -cursor_name left_ptr

# Load polybar
pkill polybar
polybar -c ~/.config/bspwm/polybar top &

# Load btops to cleanup workspaces
btops &
