#!/usr/bin/env bash

echo "Updating dotfiles..."
git pull
git submodule update

echo
echo "Setting up dotfiles with dotbot..."
read -p "Press enter to continue"
./install base

echo
echo "Executing Ansible to setup machine..."
read -p "Press enter to continue"
pushd ansible > /dev/null
ansible-playbook -K -i inventory system.yml
popd > /dev/null

echo
echo "Setting up dotfiles with dotbot, again..."
read -p "Press enter to continue"
./install base

echo
echo "Installed new system, it might be wise to re-open the console..."
