#!/bin/sh
FONT='Roboto:Regular:size=8'
conky -c "/home/cumpsd/.dzstatus" | dzen2 -bg "#2f343f" -ta right -w 640 -h 18 -x 726 -y -1 -fn $FONT &
conky -c "/home/cumpsd/.dzwin" | dzen2 -bg "#2f343f" -ta left -w 726 -h 18 -x 0 -y -1 -fn $FONT &
exit
