#! /bin/sh

###################
## CONFIGURATION ##
###################

## workspace name
bspc monitor -d 'shell' 'web' 'social' 'code' 'gfx' 'file' 'rdp' 'media' 'gaming'

## common bspwm configuration
bspc config border_width            2
bspc config window_gap         	    16
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config top_padding             42

bspc config focused_border_color    "#d8dee8"
bspc config normal_border_color     "#2f343f"

###########
## RULES ##
###########

## need to be floating
bspc rule -a Viewnior state=floating center=on
bspc rule -a feh state=floating follow=on
bspc rule -a Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating center=on # Authy
bspc rule -a chrome_app_list state=floating

## don't manage Conky
bspc rule -a Conky state=floating manage=off

###############
## AUTOSTART ##
###############

# Update betterlockscreen with current wallpaper
betterlockscreen -u ~/.wallpaper.jpg &

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

# Reload compton
pkill compton
compton -b &

# Start urxvt deamon
urxvtd -q &

# Start udiskie deamon
udiskie &

# Start keybind daemon (sxhkd)
pkill sxhkd
sxhkd &

# Start music player
mpd &

# Reload the xsettingsd, a minimal X settings daemon
pkill xsettingsd
xsettingsd &

# Set the wallpaper
feh --bg-fill ~/.wallpaper.jpg

# Start notification manager (dunst)
pkill dunst
dunst &

# Reload the cursor theme
xsetroot -cursor_name left_ptr

# Load polybar
pkill polybar
polybar -c ~/.config/bspwm/polybar top &

# Load btops to cleanup workspaces
btops &

# Load volnotify
volnoti &
